Another squeal issue
     Failure/Error: expect { Site.send_trial_will_expire }.to
change(ActionMailer::Base.deliveries, :size).by(@sites_in_trial.size)
     NoMethodError:
       undefined method `relation' for
#<Arel::Nodes::NamedFunction:0x007fc9edfdc2d0>
     # ./app/models/site_modules/invoice.rb:17:in `block in
send_trial_will_expire'
     # ./app/models/site_modules/invoice.rb:16:in `each'
     # ./app/models/site_modules/invoice.rb:16:in
`send_trial_will_expire'
     # ./spec/models/site_modules/invoice_spec.rb:29:in `block (5
levels) in <top (required)>'
     # ./spec/models/site_modules/invoice_spec.rb:29:in `block (4
levels) in <top (required)>'